export const projects = [{
        title: 'CHATROOM',
        description: "The first chat application i made. i used database mysql to store the messages.",
        image: '/images/php chat app.svg',
        tags: ['HTML', 'CSS', "JS", "PHP", "Mysql"],
        source: 'https://github.com/vidhanshu/chat-room-php',
        visit: 'https://vidhanshu.000webhostapp.com/',
        id: 0,
    }, {
        title: 'SYSTEM',
        description: "LIC management system is the system made using C++ Object oriented programming and file handling in c++",
        image: '/images/LIC.svg',
        tags: ['c++', 'c++ oops', "c++ file handling"],
        source: 'https://github.com/vidhanshu/LIC',
        visit: 'https://github.com/vidhanshu/LIC/blob/master/LIC.cpp',
        id: 1,
    },
    {
        title: 'Musify',
        description: "This is Musify the music player.",
        image: '/images/Musify.svg',
        tags: ['HTML', "CSS", 'JavaScript', "HTML Audio"],
        source: 'https://github.com/vidhanshu/Musify',
        visit: 'https://musify-ten.vercel.app/',
        id: 2,
    },
    {
        title: 'Vmovie',
        description: "Vmovie web-app build with React.js where you will get updates related to latest movies, you can watch trailors, get known with trending actors,movies and many more",
        image: '/images/vmovie.svg',
        tags: ['React', 'REST API', 'API'],
        source: 'https://github.com/vidhanshu/vmovie',
        visit: 'https://vmovie.vercel.app/',
        id: 3,
    },
    {
        title: 'Netflix clone',
        description: "Netflix clone made using react just for the practice of implementing search using local api:",
        image: '/images/netflix-clone.svg',
        tags: ['React', 'REST API', 'API'],
        source: 'https://github.com/vidhanshu/vmovie',
        visit: 'https://vmovie.vercel.app/',
        id: 4,
    },
    {
        title: 'Vnotes',
        description: "Vnote is notes app where you can note anything you want and can mark as done if you completed with it",
        image: '/images/vnotes.svg',
        tags: ['React', "DSA", "javascript"],
        source: 'https://github.com/vidhanshu/Vnotes',
        visit: 'https://vnotes.vercel.app/',
        id: 5,
    },
    {
        title: 'BITS IT',
        description: "I participated in the BITS IT FORUM WEBSITE MAKING compition. duration was 3 hours, and I made this in 3 hours. And i was 1st Runner up",
        image: '/images/3hour competition.svg',
        tags: ['HTML', "JS", "CSS"],
        source: 'https://github.com/vidhanshu/bitsit',
        visit: 'https://vidhanshu.github.io/bitsit/',
        id: 6,
    },
    {
        title: 'CoderX',
        description: "made for practice purpose made using HTML,CSS & js also used google map API.",
        image: '/images/coderX.svg',
        tags: ['HTML', "JS", "CSS"],
        source: 'https://github.com/vidhanshu/coderX',
        visit: 'https://vidhanshu.github.io/coderX/',
        id: 7,
    },
    {
        title: 'Vid hack',
        description: "vidhack is hackthon website with cool dark design and superb components made using HTML,CSS & js also used google map API.",
        image: '/images/first.svg',
        tags: ['HTML', "JS", "CSS"],
        source: 'https://github.com/vidhanshu/vidhacks.github.io',
        visit: 'https://vidhanshu.github.io/vidhacks.github.io/',
        id: 8,
    },
    {
        title: 'Tennis Game',
        description: "This Tennis game which i made using html5 canvas.",
        image: '/images/travel-app-1.svg',
        tags: ['HTML', "CSS", 'JavaScript', "HTML5 canvas"],
        source: 'https://github.com/vidhanshu/Tennis.github.io',
        visit: 'https://vidhanshu.github.io/Tennis.github.io/',
        id: 9,
    },
    {
        title: 'Tic Tac Toe Game',
        description: "The first game that i made using HTML,CSS and JS only.",
        image: '/images/tic tac toe.svg',
        tags: ['HTML', "CSS", 'JavaScript'],
        source: "https://github.com/vidhanshu/tictactoe.github.io",
        visit: 'https://vidhanshu.github.io/tictactoe.github.io/',
        id: 10,
    },
    {
        title: 'RGB quize',
        description: "The quize app where you can test your rgb knowledge build with simple HTML,CSS & js.",
        image: '/images/rgb.svg',
        tags: ['HTML', "CSS", 'JavaScript'],
        source: "https://github.com/vidhanshu/RGBquize",
        visit: 'https://rgb-quize.vercel.app',
        id: 11,
    },
    {
        title: 'Vquize',
        description: "The quize app where you can test your Gk knowledge and know your score immediatly build using React.js",
        image: '/images/gk-quize.svg',
        tags: ["React.js", 'HTML', "CSS", 'JavaScript'],
        source: "https://github.com/vidhanshu/vquize",
        visit: 'https://vquize.vercel.app',
        id: 12,
    },
    {
        title: 'First-website',
        description: "First website that i made during learning phase using HTML,CSS & js also used google map API.",
        image: '/images/first.svg',
        tags: ['HTML', "CSS", 'JavaScript'],
        source: "https://github.com/vidhanshu/First_website",
        visit: 'https://vidhanshu.github.io/First_website/',
        id: 13,
    },
    {
        title: 'Vtravel',
        description: "Vtravel app is the app where you can book your trip for next holidays.",
        image: '/images/travel-app.svg',
        tags: ["React.js", 'HTML', "CSS", 'JavaScript'],
        source: "https://github.com/vidhanshu/travel",
        visit: 'https://travel-7wt1yeekh-vidhanshu.vercel.app/',
        id: 14,
    },
    {
        title: 'Portfolio',
        description: "This is my own personal portfolio website.",
        image: '/images/myportfolio.svg',
        tags: ["React.js", 'HTML', "CSS", 'JavaScript'],
        source: "https://github.com/vidhanshu/travel",
        visit: 'https://vidhanshu-portfolio.vercel.app',
        id: 15,
    },
    {
        title: 'Loading animation',
        description: "Beautiful loading animation using css",
        image: '/images/loading animation.svg',
        tags: ['HTML', "CSS", 'JavaScript'],
        source: "https://github.com/vidhanshu/loading-animation",
        visit: 'https://vidhanshu.github.io/loading-animation/',
        id: 16,
    },
];

export const TimeLineData = [
    { year: 2019, text: 'chilling', },
    { year: 2020, text: 'Started my journey', },
    { year: 2021, text: 'Learnt programming language', },
    { year: 2022, text: 'built simple projects', },
    { year: 'currently', text: 'Doing competative programing & DSA', },
    { year: 'Future', text: 'Become successfull software engineer', },
];